"""
CodeGen backends for NodeCanvas.
Supports Python, C, C++, WASM (Emscripten), and Rust.
"""
from typing import List, Dict, Any, Optional
from dataclasses import dataclass


@dataclass
class CodeGenConfig:
    """Configuration for code generation"""
    function_name: str = "execute_graph"
    include_audio: bool = True
    include_ui: bool = False
    ui_data: Optional[Dict] = None
    variables: Optional[Dict] = None
    standalone: bool = True  # Include main() / entry point


class CBackend:
    """Generate C code from IRModule using SDL2 for audio"""
    
    # Channel name to index mapping
    CHANNELS = ["Music", "Effect", "Voice", "UI", "Ambient", "Custom1", "Custom2", "Custom3"]
    
    def __init__(self, ir_module, config: CodeGenConfig = None):
        self.ir = ir_module
        self.config = config or CodeGenConfig()
        
    def generate(self) -> str:
        """Generate C code from IR"""
        lines = []
        
        # Header
        lines.extend([
            '/* Generated by NodeCanvas */',
            '#include <stdio.h>',
            '#include <stdlib.h>',
            '#include <string.h>',
            '#include <stdbool.h>',
            '#include <math.h>',
        ])
        
        if self.config.include_audio:
            lines.extend([
                '',
                '/* SDL2 Audio (requires SDL2 and SDL2_mixer) */',
                '#include <SDL2/SDL.h>',
                '#include <SDL2_mixer/SDL_mixer.h>',
                '',
                '#define NUM_CHANNELS 8',
                'static Mix_Chunk* _sounds[256];',
                'static int _sound_count = 0;',
                '',
                'void audio_init() {',
                '    if (SDL_Init(SDL_INIT_AUDIO) < 0) {',
                '        fprintf(stderr, "SDL init failed: %s\\n", SDL_GetError());',
                '        return;',
                '    }',
                '    if (Mix_OpenAudio(44100, MIX_DEFAULT_FORMAT, 2, 2048) < 0) {',
                '        fprintf(stderr, "SDL_mixer init failed: %s\\n", Mix_GetError());',
                '        return;',
                '    }',
                '    Mix_AllocateChannels(NUM_CHANNELS);',
                '}',
                '',
                'void audio_cleanup() {',
                '    for (int i = 0; i < _sound_count; i++) {',
                '        if (_sounds[i]) Mix_FreeChunk(_sounds[i]);',
                '    }',
                '    Mix_CloseAudio();',
                '    SDL_Quit();',
                '}',
                '',
                'int channel_index(const char* name) {',
                '    if (strcmp(name, "Music") == 0) return 0;',
                '    if (strcmp(name, "Effect") == 0) return 1;',
                '    if (strcmp(name, "Voice") == 0) return 2;',
                '    if (strcmp(name, "UI") == 0) return 3;',
                '    if (strcmp(name, "Ambient") == 0) return 4;',
                '    if (strcmp(name, "Custom1") == 0) return 5;',
                '    if (strcmp(name, "Custom2") == 0) return 6;',
                '    if (strcmp(name, "Custom3") == 0) return 7;',
                '    return 1; /* Default to Effect */',
                '}',
                '',
                'void audio_play(const char* path, const char* channel, bool loop) {',
                '    Mix_Chunk* sound = Mix_LoadWAV(path);',
                '    if (!sound) {',
                '        fprintf(stderr, "Failed to load %s: %s\\n", path, Mix_GetError());',
                '        return;',
                '    }',
                '    _sounds[_sound_count++] = sound;',
                '    int ch = channel_index(channel);',
                '    Mix_PlayChannel(ch, sound, loop ? -1 : 0);',
                '    printf("[Audio] Playing %s on channel %s\\n", path, channel);',
                '}',
                '',
                'void audio_stop(const char* channel) {',
                '    if (strcmp(channel, "All") == 0) {',
                '        Mix_HaltChannel(-1);',
                '    } else {',
                '        Mix_HaltChannel(channel_index(channel));',
                '    }',
                '    printf("[Audio] Stopped channel %s\\n", channel);',
                '}',
            ])
        
        # Variables section
        lines.extend([
            '',
            '/* Variables */',
        ])
        if self.config.variables:
            for name, info in self.config.variables.items():
                var_type = info.get('type', 'any') if isinstance(info, dict) else 'any'
                value = info.get('value', None) if isinstance(info, dict) else info
                c_type, c_val = self._to_c_type_and_value(var_type, value)
                lines.append(f'{c_type} var_{self._safe_name(name)} = {c_val};')
        
        # Main function
        lines.extend([
            '',
            f'void {self.config.function_name}() {{',
        ])
        
        # Visit nodes
        for node in self.ir.nodes:
            node_lines = self._visit_node(node)
            lines.extend(['    ' + line for line in node_lines])
        
        lines.append('}')
        
        # Entry point
        if self.config.standalone:
            lines.extend([
                '',
                'int main(int argc, char* argv[]) {',
            ])
            if self.config.include_audio:
                lines.append('    audio_init();')
            lines.extend([
                f'    {self.config.function_name}();',
            ])
            if self.config.include_audio:
                lines.extend([
                    '    /* Keep alive for audio */',
                    '    printf("Press Enter to exit...\\n");',
                    '    getchar();',
                    '    audio_cleanup();',
                ])
            lines.extend([
                '    return 0;',
                '}',
            ])
        
        return '\n'.join(lines)
    
    def _safe_name(self, name: str) -> str:
        """Convert variable name to C-safe identifier"""
        return ''.join(c if c.isalnum() else '_' for c in name)
    
    def _to_c_type_and_value(self, var_type: str, value: Any) -> tuple:
        """Convert Python type/value to C type and literal"""
        if var_type == 'int':
            return ('int', str(value if value is not None else 0))
        elif var_type == 'float':
            return ('double', str(float(value) if value is not None else 0.0))
        elif var_type == 'bool':
            return ('bool', 'true' if value else 'false')
        elif var_type in ('string', 'audio', 'image'):
            escaped = str(value or '').replace('\\', '\\\\').replace('"', '\\"')
            return ('const char*', f'"{escaped}"')
        else:
            return ('void*', 'NULL')
    
    def _visit_node(self, node) -> List[str]:
        """Visit a single IR node and emit C code"""
        try:
            from py_editor.core.ir import ConstValue, Add, Subtract, Multiply, Divide, Print, Return, SetVar, GetVar, Custom
        except ImportError:
            from ..core.ir import ConstValue, Add, Subtract, Multiply, Divide, Print, Return, SetVar, GetVar, Custom
        
        kind = node.kind
        nid = node.id.id
        lines = [f'/* Node {nid} */']
        widget_vals = self.ir.widget_values.get(nid, {})
        
        # Helper to get input value reference
        def inp(idx):
            if kind.inputs and len(kind.inputs) > idx and kind.inputs[idx]:
                return f'node_{kind.inputs[idx].id}'
            return 'NULL'
        
        if isinstance(kind, ConstValue):
            c_type, c_val = self._to_c_type_and_value(
                kind.value.type.value if hasattr(kind.value.type, 'value') else 'any',
                kind.value.data
            )
            lines.append(f'{c_type} node_{nid} = {c_val};')
        
        elif isinstance(kind, Add):
            lines.append(f'double node_{nid} = {inp(0) or "0"} + {inp(1) or "0"};')
        
        elif isinstance(kind, Subtract):
            lines.append(f'double node_{nid} = {inp(0) or "0"} - {inp(1) or "0"};')
        
        elif isinstance(kind, Multiply):
            lines.append(f'double node_{nid} = {inp(0) or "1"} * {inp(1) or "1"};')
        
        elif isinstance(kind, Divide):
            b = inp(1) or '1'
            lines.append(f'double node_{nid} = ({b} != 0) ? ({inp(0) or "0"} / {b}) : 0.0;')
        
        elif isinstance(kind, Print):
            val = inp(0) or '"(null)"'
            lines.append(f'printf("%s\\n", {val});')
        
        elif isinstance(kind, Return):
            lines.append(f'return; /* {inp(0)} */')
        
        elif isinstance(kind, SetVar):
            var_name = widget_vals.get('name', 'var')
            lines.append(f'var_{self._safe_name(var_name)} = {inp(0)};')
        
        elif isinstance(kind, GetVar):
            var_name = widget_vals.get('name', 'var')
            lines.append(f'auto node_{nid} = var_{self._safe_name(var_name)};')
        
        elif isinstance(kind, Custom):
            name = kind.name
            
            # === Flow Control ===
            if name == 'OnStart':
                lines.append('/* OnStart - entry point */')
            
            elif name == 'Branch':
                cond = inp(0) or 'false'
                lines.append(f'if ({cond}) {{')
                lines.append(f'    /* True branch */')
                lines.append(f'}} else {{')
                lines.append(f'    /* False branch */')
                lines.append(f'}}')
            
            elif name == 'Sequence':
                lines.append('/* Sequence - executes branches in order */')
            
            elif name == 'ForLoop':
                start = widget_vals.get('start', 0)
                end = widget_vals.get('end', 10)
                lines.append(f'for (int i_{nid} = {start}; i_{nid} < {end}; i_{nid}++) {{')
                lines.append(f'    int node_{nid}_index = i_{nid};')
                lines.append(f'    /* Loop body */')
                lines.append(f'}}')
            
            elif name == 'WhileLoop':
                lines.append(f'while (true) {{ /* Condition check needed */')
                lines.append(f'    /* Loop body */')
                lines.append(f'    break; /* Safety: remove when condition implemented */')
                lines.append(f'}}')
            
            elif name == 'ForEachLoop':
                lines.append(f'/* ForEachLoop - iterate over collection */')
                lines.append(f'for (int i_{nid} = 0; i_{nid} < list_len; i_{nid}++) {{')
                lines.append(f'    /* Loop body with item access */')
                lines.append(f'}}')
            
            # === Comparison ===
            elif name in ('Equal', 'NotEqual', 'LessThan', 'GreaterThan', 'LessThanOrEqual', 'GreaterThanOrEqual'):
                a = widget_vals.get('a', 0) if not kind.inputs or not kind.inputs[0] else inp(0)
                b = widget_vals.get('b', 0) if len(kind.inputs) < 2 or not kind.inputs[1] else inp(1)
                ops = {'Equal': '==', 'NotEqual': '!=', 'LessThan': '<', 
                       'GreaterThan': '>', 'LessThanOrEqual': '<=', 'GreaterThanOrEqual': '>='}
                lines.append(f'bool node_{nid} = ({a} {ops[name]} {b});')
            
            elif name in ('And', 'Or'):
                a = inp(0) or 'false'
                b = inp(1) or 'false'
                op = '&&' if name == 'And' else '||'
                lines.append(f'bool node_{nid} = ({a} {op} {b});')
            
            elif name == 'Not':
                lines.append(f'bool node_{nid} = !{inp(0) or "false"};')
            
            # === Math ===
            elif name == 'Abs':
                lines.append(f'double node_{nid} = fabs({inp(0) or "0"});')
            
            elif name == 'Min':
                lines.append(f'double node_{nid} = fmin({inp(0) or "0"}, {inp(1) or "0"});')
            
            elif name == 'Max':
                lines.append(f'double node_{nid} = fmax({inp(0) or "0"}, {inp(1) or "0"});')
            
            elif name == 'Clamp':
                val = inp(0) or '0'
                min_v = widget_vals.get('min', 0)
                max_v = widget_vals.get('max', 1)
                lines.append(f'double node_{nid} = fmax({min_v}, fmin({max_v}, {val}));')
            
            elif name in ('Floor', 'Ceil', 'Round'):
                func = name.lower()
                lines.append(f'double node_{nid} = {func}({inp(0) or "0"});')
            
            elif name == 'Modulo':
                lines.append(f'int node_{nid} = (int){inp(0) or "0"} % (int){inp(1) or "1"};')
            
            elif name == 'Power':
                lines.append(f'double node_{nid} = pow({inp(0) or "0"}, {inp(1) or "1"});')
            
            elif name == 'Sqrt':
                lines.append(f'double node_{nid} = sqrt({inp(0) or "0"});')
            
            elif name == 'Lerp':
                lines.append(f'double node_{nid} = {inp(0) or "0"} + ({inp(1) or "1"} - {inp(0) or "0"}) * {inp(2) or "0.5"};')
            
            elif name == 'RandomNumber':
                min_v = widget_vals.get('min', 0)
                max_v = widget_vals.get('max', 100)
                lines.append(f'double node_{nid} = {min_v} + ((double)rand() / RAND_MAX) * ({max_v} - {min_v});')
            
            # === Conversion ===
            elif name == 'ToInt':
                lines.append(f'int node_{nid} = (int){inp(0) or "0"};')
            
            elif name == 'ToFloat':
                lines.append(f'double node_{nid} = (double){inp(0) or "0"};')
            
            elif name == 'ToBool':
                lines.append(f'bool node_{nid} = (bool){inp(0) or "0"};')
            
            elif name == 'ToString':
                arg0 = inp(0) or '""'
                lines.append(f'char node_{nid}[256]; sprintf(node_{nid}, "%s", {arg0});')
            
            # === String Operations ===
            elif name == 'StringConcat':
                arg0 = inp(0) or '""'
                arg1 = inp(1) or '""'
                lines.append(f'char node_{nid}[512];')
                lines.append(f'sprintf(node_{nid}, "%s%s", {arg0}, {arg1});')
            
            elif name == 'StringLength':
                arg0 = inp(0) or '""'
                lines.append(f'int node_{nid} = strlen({arg0});')
            
            elif name == 'StringContains':
                arg0 = inp(0) or '""'
                arg1 = inp(1) or '""'
                lines.append(f'bool node_{nid} = (strstr({arg0}, {arg1}) != NULL);')
            
            # === Audio ===
            elif name == 'PlaySound':
                file_path = inp(0) if kind.inputs and kind.inputs[0] else f'"{widget_vals.get("file_path", "")}"'
                channel = widget_vals.get('channel', 'Effect')
                if isinstance(channel, int):
                    channel = self.CHANNELS[channel] if channel < len(self.CHANNELS) else 'Effect'
                loop = 'true' if widget_vals.get('loop') in ('Yes', True) else 'false'
                lines.append(f'audio_play({file_path}, "{channel}", {loop});')
            
            elif name == 'StopSound':
                channel = widget_vals.get('channel', 'All')
                lines.append(f'audio_stop("{channel}");')
            
            # === UI ===
            elif name == 'SetUIScreen':
                screen = widget_vals.get('screenName', '')
                lines.append(f'/* SetUIScreen: {screen} */')
            
            elif name == 'SetUIText':
                lines.append(f'/* SetUIText */')
            
            elif name == 'SetUIProgress':
                lines.append(f'/* SetUIProgress */')
            
            elif name == 'SetUIVisibility':
                lines.append(f'/* SetUIVisibility */')
            
            # === Variables ===
            elif name == 'GetVariable':
                var_name = widget_vals.get('name', 'var')
                lines.append(f'auto node_{nid} = var_{self._safe_name(var_name)};')
            
            elif name == 'SetVariable':
                var_name = widget_vals.get('name', 'var')
                lines.append(f'var_{self._safe_name(var_name)} = {inp(0)};')
            
            # === Const Nodes ===
            elif name in ('ConstInt', 'ConstFloat', 'ConstBool', 'ConstString'):
                val = widget_vals.get('value', 0)
                if name == 'ConstInt':
                    lines.append(f'int node_{nid} = {val};')
                elif name == 'ConstFloat':
                    lines.append(f'double node_{nid} = {val};')
                elif name == 'ConstBool':
                    lines.append(f'bool node_{nid} = {"true" if val else "false"};')
                elif name == 'ConstString':
                    escaped = str(val).replace('\\', '\\\\').replace('"', '\\"')
                    lines.append(f'const char* node_{nid} = "{escaped}";')
            
            # === Collections (simplified - full implementation would need linked lists) ===
            elif name == 'CreateList':
                lines.append(f'/* CreateList - arrays not directly supported in generated C */')
                lines.append(f'void* node_{nid} = NULL; /* Use custom array implementation */')
            
            elif name in ('ListAppend', 'ListGet', 'ListSet', 'ListLength', 'ListFirst', 'ListLast'):
                lines.append(f'/* {name} - collection operation */')
                lines.append(f'void* node_{nid} = NULL;')
            
            elif name in ('CreateStruct', 'StructGet', 'StructSet'):
                lines.append(f'/* {name} - struct operation */')
                lines.append(f'void* node_{nid} = NULL;')
            
            elif name in ('CreateDict', 'DictGet', 'DictSet', 'DictKeys', 'DictHasKey'):
                lines.append(f'/* {name} - dict operation */')
                lines.append(f'void* node_{nid} = NULL;')
            
            # === Default ===
            else:
                lines.append(f'/* TODO: {name} - not yet implemented */')
                lines.append(f'void* node_{nid} = NULL;')
        
        else:
            lines.append(f'/* Unknown node type */')
        
        return lines


class CppBackend:
    """Generate C++ code from IRModule using SDL2"""
    
    CHANNELS = ["Music", "Effect", "Voice", "UI", "Ambient", "Custom1", "Custom2", "Custom3"]
    
    def __init__(self, ir_module, config: CodeGenConfig = None):
        self.ir = ir_module
        self.config = config or CodeGenConfig()
        self.c_backend = CBackend(ir_module, config)  # Reuse C backend logic
    
    def generate(self) -> str:
        """Generate C++ code from IR"""
        lines = []
        
        lines.extend([
            '/* Generated by NodeCanvas */',
            '#include <iostream>',
            '#include <string>',
            '#include <map>',
            '#include <vector>',
            '#include <any>',
            '#include <cmath>',
            '#include <cstdlib>',
        ])
        
        if self.config.include_audio:
            lines.extend([
                '',
                '// SDL2 Audio',
                '#include <SDL2/SDL.h>',
                '#include <SDL2_mixer/SDL_mixer.h>',
                '',
                'namespace Audio {',
                '    std::map<std::string, int> channelMap = {',
                '        {"Music", 0}, {"Effect", 1}, {"Voice", 2}, {"UI", 3},',
                '        {"Ambient", 4}, {"Custom1", 5}, {"Custom2", 6}, {"Custom3", 7}',
                '    };',
                '    std::vector<Mix_Chunk*> sounds;',
                '    ',
                '    void init() {',
                '        SDL_Init(SDL_INIT_AUDIO);',
                '        Mix_OpenAudio(44100, MIX_DEFAULT_FORMAT, 2, 2048);',
                '        Mix_AllocateChannels(8);',
                '    }',
                '    ',
                '    void cleanup() {',
                '        for (auto* s : sounds) if (s) Mix_FreeChunk(s);',
                '        Mix_CloseAudio();',
                '        SDL_Quit();',
                '    }',
                '    ',
                '    void play(const std::string& path, const std::string& channel = "Effect", bool loop = false) {',
                '        Mix_Chunk* sound = Mix_LoadWAV(path.c_str());',
                '        if (!sound) { std::cerr << "Failed to load: " << path << std::endl; return; }',
                '        sounds.push_back(sound);',
                '        int ch = channelMap.count(channel) ? channelMap[channel] : 1;',
                '        Mix_PlayChannel(ch, sound, loop ? -1 : 0);',
                '        std::cout << "[Audio] Playing " << path << " on " << channel << std::endl;',
                '    }',
                '    ',
                '    void stop(const std::string& channel = "All") {',
                '        if (channel == "All") Mix_HaltChannel(-1);',
                '        else if (channelMap.count(channel)) Mix_HaltChannel(channelMap[channel]);',
                '    }',
                '}',
            ])
        
        # Variables
        lines.extend(['', '// Variables'])
        if self.config.variables:
            for name, info in self.config.variables.items():
                var_type = info.get('type', 'any') if isinstance(info, dict) else 'any'
                value = info.get('value', None) if isinstance(info, dict) else info
                cpp_type, cpp_val = self._to_cpp_type_and_value(var_type, value)
                safe_name = self.c_backend._safe_name(name)
                lines.append(f'{cpp_type} var_{safe_name} = {cpp_val};')
        
        # Main function
        lines.extend([
            '',
            f'void {self.config.function_name}() {{',
        ])
        
        for node in self.ir.nodes:
            node_lines = self._visit_node(node)
            lines.extend(['    ' + line for line in node_lines])
        
        lines.append('}')
        
        # Entry point
        if self.config.standalone:
            lines.extend([
                '',
                'int main(int argc, char* argv[]) {',
            ])
            if self.config.include_audio:
                lines.append('    Audio::init();')
            lines.extend([
                f'    {self.config.function_name}();',
            ])
            if self.config.include_audio:
                lines.extend([
                    '    std::cout << "Press Enter to exit..." << std::endl;',
                    '    std::cin.get();',
                    '    Audio::cleanup();',
                ])
            lines.extend([
                '    return 0;',
                '}',
            ])
        
        return '\n'.join(lines)
    
    def _to_cpp_type_and_value(self, var_type: str, value) -> tuple:
        if var_type == 'int':
            return ('int', str(value if value is not None else 0))
        elif var_type == 'float':
            return ('double', str(float(value) if value is not None else 0.0))
        elif var_type == 'bool':
            return ('bool', 'true' if value else 'false')
        elif var_type in ('string', 'audio', 'image'):
            escaped = str(value or '').replace('\\', '\\\\').replace('"', '\\"')
            return ('std::string', f'"{escaped}"')
        else:
            return ('std::any', '{}')
    
    def _visit_node(self, node) -> List[str]:
        """Reuse C backend with C++ syntax adjustments"""
        # Delegate most logic but adjust output names
        try:
            from py_editor.core.ir import Custom
        except ImportError:
            from ..core.ir import Custom
        
        kind = node.kind
        nid = node.id.id
        widget_vals = self.ir.widget_values.get(nid, {})
        
        if isinstance(kind, Custom):
            if kind.name == 'PlaySound':
                file_path = f'node_{kind.inputs[0].id}' if kind.inputs and kind.inputs[0] else f'"{widget_vals.get("file_path", "")}"'
                channel = widget_vals.get('channel', 'Effect')
                if isinstance(channel, int):
                    channel = self.CHANNELS[channel] if channel < len(self.CHANNELS) else 'Effect'
                loop = 'true' if (widget_vals.get('loop') in ('Yes', True)) else 'false'
                return [f'Audio::play({file_path}, "{channel}", {loop});']
            elif kind.name == 'StopSound':
                return [f'Audio::stop("{widget_vals.get("channel", "All")}");']
        
        # Fall back to C backend logic for other nodes
        return self.c_backend._visit_node(node)


class WasmBackend:
    """Generate C code for Emscripten/WebAssembly compilation"""
    
    def __init__(self, ir_module, config: CodeGenConfig = None):
        self.ir = ir_module
        self.config = config or CodeGenConfig()
        self.c_backend = CBackend(ir_module, config)
    
    def generate(self) -> str:
        """Generate WASM-compatible C code"""
        lines = []
        
        lines.extend([
            '/* Generated by NodeCanvas for WebAssembly */',
            '#include <emscripten.h>',
            '#include <stdio.h>',
            '#include <stdbool.h>',
            '',
            '/* JavaScript audio bridge */',
            'EM_JS(void, js_audio_play, (const char* path, const char* channel, bool loop), {',
            '    const audioPath = UTF8ToString(path);',
            '    const audioChannel = UTF8ToString(channel);',
            '    console.log("[Audio] Playing:", audioPath, "on", audioChannel);',
            '    // Create and play audio element',
            '    const audio = new Audio(audioPath);',
            '    audio.loop = loop;',
            '    audio.play().catch(e => console.error("Audio error:", e));',
            '});',
            '',
            'EM_JS(void, js_audio_stop, (const char* channel), {',
            '    console.log("[Audio] Stop:", UTF8ToString(channel));',
            '    // Would need audio element tracking to implement fully',
            '});',
            '',
            'void audio_play(const char* path, const char* channel, bool loop) {',
            '    js_audio_play(path, channel, loop);',
            '}',
            '',
            'void audio_stop(const char* channel) {',
            '    js_audio_stop(channel);',
            '}',
        ])
        
        # Variables
        lines.extend(['', '/* Variables */'])
        if self.config.variables:
            for name, info in self.config.variables.items():
                var_type = info.get('type', 'any') if isinstance(info, dict) else 'any'
                value = info.get('value', None) if isinstance(info, dict) else info
                c_type, c_val = self.c_backend._to_c_type_and_value(var_type, value)
                lines.append(f'{c_type} var_{self.c_backend._safe_name(name)} = {c_val};')
        
        # Main function - exported for JavaScript
        lines.extend([
            '',
            f'EMSCRIPTEN_KEEPALIVE',
            f'void {self.config.function_name}() {{',
        ])
        
        for node in self.ir.nodes:
            node_lines = self.c_backend._visit_node(node)
            lines.extend(['    ' + line for line in node_lines])
        
        lines.append('}')
        
        # Entry point
        if self.config.standalone:
            lines.extend([
                '',
                'int main() {',
                f'    {self.config.function_name}();',
                '    return 0;',
                '}',
            ])
        
        return '\n'.join(lines)
    
    def generate_html(self) -> str:
        """Generate HTML wrapper for WASM module"""
        return f'''<!DOCTYPE html>
<html>
<head>
    <title>NodeCanvas WASM App</title>
    <style>
        body {{ font-family: sans-serif; margin: 20px; background: #1e1e1e; color: #fff; }}
        #output {{ background: #2d2d30; padding: 10px; border-radius: 4px; white-space: pre; font-family: monospace; }}
    </style>
</head>
<body>
    <h1>NodeCanvas WASM App</h1>
    <div id="output">Loading...</div>
    <script>
        var Module = {{
            onRuntimeInitialized: function() {{
                document.getElementById('output').textContent = 'Ready! Running graph...';
                Module._{self.config.function_name}();
            }},
            print: function(text) {{
                var output = document.getElementById('output');
                output.textContent += '\\n' + text;
            }}
        }};
    </script>
    <script src="{self.config.function_name}.js"></script>
</body>
</html>'''

