"""
Python Codegen Backend

Generates standalone Python code from IR with pygame audio runtime.
"""
from typing import List

try:
    from py_editor.core.ir import (
        IRModule, NodeId, Value, ValueType,
        ConstValue, Add, Subtract, Multiply, Divide, Return, Print, SetVar, GetVar, Custom
    )
except ImportError:
    try:
        from ..core.ir import (
            IRModule, NodeId, Value, ValueType,
            ConstValue, Add, Subtract, Multiply, Divide, Return, Print, SetVar, GetVar, Custom
        )
    except ImportError:
        from core.ir import (
            IRModule, NodeId, Value, ValueType,
            ConstValue, Add, Subtract, Multiply, Divide, Return, Print, SetVar, GetVar, Custom
        )


class PythonCodegen:
    """Generate standalone Python code from IRModule"""
    
    def __init__(self, ir_module: IRModule, function_name: str = "execute_graph"):
        self.ir = ir_module
        self.function_name = function_name
        
    def generate(self) -> str:
        """Walk the IR and emit Python code"""
        lines = []
        
        # Header
        lines.extend([
            '"""Generated by NodeCanvas - Standalone Python Script"""',
            '',
            '# Audio runtime (requires pygame)',
            'try:',
            '    import pygame',
            '    pygame.mixer.init(frequency=44100, size=-16, channels=2, buffer=512)',
            '    pygame.mixer.set_num_channels(8)',
            '    _AUDIO_CHANNELS = {',
            '        "Music": pygame.mixer.Channel(0),',
            '        "Effect": pygame.mixer.Channel(1),',
            '        "Voice": pygame.mixer.Channel(2),',
            '        "UI": pygame.mixer.Channel(3),',
            '        "Ambient": pygame.mixer.Channel(4),',
            '        "Custom1": pygame.mixer.Channel(5),',
            '        "Custom2": pygame.mixer.Channel(6),',
            '        "Custom3": pygame.mixer.Channel(7),',
            '    }',
            '    _AUDIO_SOUNDS = {}',
            '    def _audio_play(path, channel="Effect", loop=False):',
            '        if path not in _AUDIO_SOUNDS:',
            '            _AUDIO_SOUNDS[path] = pygame.mixer.Sound(path)',
            '        _AUDIO_CHANNELS.get(channel, _AUDIO_CHANNELS["Effect"]).play(_AUDIO_SOUNDS[path], loops=-1 if loop else 0)',
            '    def _audio_stop(channel="All"):',
            '        if channel == "All": pygame.mixer.stop()',
            '        elif channel in _AUDIO_CHANNELS: _AUDIO_CHANNELS[channel].stop()',
            'except ImportError:',
            '    def _audio_play(path, channel="Effect", loop=False): print(f"[Audio] pygame unavailable: {path}")',
            '    def _audio_stop(channel="All"): pass',
            '',
            'def ' + self.function_name + '():',
            '    """Execute the node graph"""',
            '    # Variables storage',
            '    variables = {}',
            '    ',
        ])
        
        # Visit each node in order
        for node in self.ir.nodes:
            node_lines = self._visit_node(node)
            lines.extend(['    ' + line for line in node_lines])
        
        lines.extend([
            '',
            '',
            'if __name__ == "__main__":',
            f'    result = {self.function_name}()',
            '    print(f"Result: {result}")',
            '    # Keep alive for audio',
            '    try:',
            '        import time',
            '        while True: time.sleep(0.1)',
            '    except KeyboardInterrupt:',
            '        pass',
        ])
        
        return '\n'.join(lines)
    
    def _visit_node(self, node) -> List[str]:
        """Visit a single IR node and emit Python code"""
        kind = node.kind
        nid = node.id.id
        lines = [f'# Node {nid}: {type(kind).__name__}']
        
        # ConstValue
        if isinstance(kind, ConstValue):
            lines.append(f'node_{nid} = {kind.value.data}')
        
        # Binary ops
        elif isinstance(kind, Add):
            a = f'node_{kind.a.id}' if kind.a else '0'
            b = f'node_{kind.b.id}' if kind.b else '0'
            lines.append(f'node_{nid} = {a} + {b}')
        
        elif isinstance(kind, Subtract):
            a = f'node_{kind.a.id}' if kind.a else '0'
            b = f'node_{kind.b.id}' if kind.b else '0'
            lines.append(f'node_{nid} = {a} - {b}')
        
        elif isinstance(kind, Multiply):
            a = f'node_{kind.a.id}' if kind.a else '1'
            b = f'node_{kind.b.id}' if kind.b else '1'
            lines.append(f'node_{nid} = {a} * {b}')
        
        elif isinstance(kind, Divide):
            a = f'node_{kind.a.id}' if kind.a else '0'
            b = f'node_{kind.b.id}' if kind.b else '1'
            lines.append(f'node_{nid} = {a} / {b} if {b} != 0 else float("inf")')
        
        # Print
        elif isinstance(kind, Print):
            val = f'node_{kind.value.id}' if kind.value else 'None'
            lines.append(f'print({val})')
            lines.append(f'node_{nid} = {val}')
        
        # Return
        elif isinstance(kind, Return):
            val = f'node_{kind.value.id}' if kind.value else 'None'
            lines.append(f'return {val}')
        
        # Variables
        elif isinstance(kind, SetVar):
            var_name = self.ir.widget_values.get(nid, {}).get('name', 'var')
            val = f'node_{kind.value.id}' if kind.value else 'None'
            lines.append(f'variables["{var_name}"] = {val}')
            lines.append(f'node_{nid} = {val}')
        
        elif isinstance(kind, GetVar):
            var_name = self.ir.widget_values.get(nid, {}).get('name', 'var')
            lines.append(f'node_{nid} = variables.get("{var_name}")')
        
        # Custom nodes - check for specific types
        elif hasattr(kind, 'name'):
            widget_vals = self.ir.widget_values.get(nid, {})
            
            if kind.name == 'PlaySound':
                # Get file path from input connection or widget
                file_path = f'node_{kind.inputs[0].id}' if kind.inputs and kind.inputs[0] else f'"{widget_vals.get("file_path", "")}"'
                channel = widget_vals.get('channel', 'Effect')
                loop_val = widget_vals.get('loop', 'No')
                loop = 'True' if (loop_val == 'Yes' or loop_val == True) else 'False'
                lines.append(f'# PlaySound: channel={channel}, loop={loop}')
                lines.append(f'_audio_play({file_path}, "{channel}", {loop})')
                lines.append(f'node_{nid} = None')
            
            elif kind.name == 'StopSound':
                channel = widget_vals.get('channel', 'All')
                lines.append(f'# StopSound: channel={channel}')
                lines.append(f'_audio_stop("{channel}")')
                lines.append(f'node_{nid} = None')
            
            else:
                lines.append(f'node_{nid} = None  # Custom node: {kind.name}')
        
        lines.append('')
        return lines


# Alias for backwards compatibility
PythonBackend = PythonCodegen

__all__ = ['PythonCodegen', 'PythonBackend']
